apiVersion: v2
name: networking
description: A Helm chart for setting up Cortex's networking dependencies
type: application
version: 0.29.0       # CORTEX_VERSION
appVersion: "0.29.0" # CORTEX_VERSION
